name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.5' # Altere para a versão desejada do Go

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test ./tests/unit/**/*
